networks:
  mappingservice:
    driver: bridge

services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    command: npm run dev
    networks:
      - mappingservice

  frontend:
    build: ./frontend
    ports:
      - "3000:5173"
    environment:
      - VITE_BACKEND_URL=http://localhost:5000
    volumes:
      - ./frontend:/app
    command: npm run dev
    networks:
      - mappingservice
